name: IncDigitalClocks
version: '${project.version}'
main: ru.incrementstudio.incdigitalclocks.IncDigitalClocks
api-version: '1.20'
authors: [IncrementStudio++]
description: Плагин на цифровые часы для турнира от Bebr0
website: incrementstudio.ru
