name: IncDigitalClocks
version: '${project.version}'
main: ru.incrementstudio.incdigitalclocks.Main
api-version: '1.20'
authors: [IncrementStudio++]
description: Плагин на цифровые часы для турнира от BeBr0
website: incrementstudio.ru
commands:
  clocks: