name: IncDigitalClocks
version: '1.0'
main: ru.incrementstudio.incdigitalclocks.Main
api-version: '1.20'
authors: [IncrementStudio++]
description: Плагин на цифровые часы для турнира от Bebr0
website: incrementstudio.ru
commands:
  clocks: